var link = {
	historicalRepeatForm: "https://docs.google.com/forms/d/e/1FAIpQLSd4QJN0osPbYRnGpxNs4kF30crFqyNNyrZv7sCyvGOHSBoZrQ/viewform",
	repeatedCoursePolicy: "https://bulletin.vcu.edu/academic-regs/ugrad/repeated-courses/",
	passFail: "https://registrar.vcu.edu/registration/registration-guide/pass-fail-grade-option/",
	passFailForm: "https://docs.google.com/forms/d/e/1FAIpQLSftpl845u3FPC2RKNbet3DWecq-iV4YaQ8B05-EvYHXw3kkbw/closedform",
	addDropWithdraw: "https://registrar.vcu.edu/registration/registration-guide/add-drop-or-withdraw/",
	dropWithdrawSFS: "https://sfs.vcu.edu/billing-and-payments/refunds/drops-and-withdrawals/",
	withdrawHowTo: 'https://docs.google.com/document/d/1T3WMr2VgOJm7UJz6tFzgJJfjeAaJksknqq-FS4Gp8rE/edit?tab=t.0#heading=h.ez68l0r9b83d',
	academicStanding: "https://bulletin.vcu.edu/academic-regs/ugrad/continuance/",
	sap: "https://sfs.vcu.edu/financial-aid/keeping-your-aid/satisfactory-academic-progress/",
	arac: "https://bulletin.vcu.edu/academic-regs/ugrad/arac/",
	uaaAracForm: "https://uaa.vcu.edu/services/academic-policy-appeals/",
	mloa: "https://dos.vcu.edu/services/medical-leave-of-absence/",
	readmission: "https://bulletin.vcu.edu/undergraduate/undergraduate-study/admission-university/readmission-guidelines/",
	courseEvaluation: "https://www.pubapps.vcu.edu/courseeval/",
	eServices: "https://go.vcu.edu/eservices",
	genEds: "https://bulletin.vcu.edu/undergraduate/undergraduate-study/general-education-curriculum/",
	engineeringPolicies: "https://bulletin.vcu.edu/undergraduate/engineering/undergraduate-information/",
	registrationDates: "https://registrar.vcu.edu/registration/registration-guide/registration-dates/",
	registrationInstructions: "https://registrar.vcu.edu/registration/registration-guide/",
	alternativeCredit: "https://bulletin.vcu.edu/undergraduate/undergraduate-study/admission-university/additional-sources-of-credit/",
	transferEquivalents: "https://transfer.vcu.edu/transferring-credits/transfer-course-equivalents/",
	changeMajor: "https://docs.google.com/a/vcu.edu/forms/d/e/1FAIpQLScwHVA7WToKtPDdLwnIyODKpQuyO9gZo1gCg1MtVgMKi6ZcEQ/viewform",
	changeMajorRequirements: "https://academicadvising.vcu.edu/change-your-major/",
	changeMinor: "https://docs.google.com/a/vcu.edu/forms/d/e/1FAIpQLSdflGo9cbNm5Htn2JxGNS4wbUq5fAqt7zTCbop0H45h10NupQ/viewform",
	fiOverride: "https://fi.vcu.edu/resources-for-students/overrides-/",
	//fiOverrideForm: "https://docs.google.com/forms/d/e/1FAIpQLSePKFB7XjW9etDaOUBeEhpQEHdomQOEmq9KC97L3vsF2XEitg/viewform",
	override: "https://academicadvising.vcu.edu/forms/course-overrides/",
	enrollmentCancellation: "https://docs.google.com/forms/d/e/1FAIpQLSdcXxq5D5a97H6bwSwhLEC1OsYUrUAiqriXkvkVPVdG-XoI7A/viewform",
	waitlistInstructions: "https://registrar.vcu.edu/registration/registration-guide/waitlists/",
	takeCoursesElsewhere: 'https://transfer.vcu.edu/for-admitted-students/taking-courses-outside-vcu/',
	//takeCoursesElsewhereForm: "https://docs.google.com/forms/d/e/1FAIpQLSfeMDvts-gkMesw91dbNBRsjyt1O3iiUh1vLw26-rhBPfTnkw/viewform",
	requestForAssistance: "https://cm.maxient.com/reportingform.php?VirginiaCommonwealthUniv&layout_id=6",
	navigate: 'https://vcu.navigate.eab.com/app',
	overrides: 'https://academicadvising.vcu.edu/forms/course-overrides/',
	timelyCare: 'https://counseling.vcu.edu/students/timelycare/',
	collegeScheduler: 'https://vcu.collegescheduler.com/entry',
	
	majorMaps: 'https://majormaps.vcu.edu/',
	
	terms: "https://registrar.vcu.edu/academic-schedules/schedule-of-classes/",
	miniterm: 'https://registrar.vcu.edu/registration/registration-guide/spring-miniterms/',
	jTerm: "https://winter.vcu.edu/courses/j-term/",
	intersession: "https://winter.vcu.edu/",
	summer: "https://summer.vcu.edu/summer-courses/",
	
	degreeWorks: 'https://dw-prod.ec.vcu.edu/responsiveDashboard/',
	degreeWorksSep: 'https://dw-prod.ec.vcu.edu/responsiveDashboard/plans',

	//Engineering
	engOverride: "https://egr.vcu.edu/current-students/student-services/undergraduate/#OverrideForms",
	mathAleks: "https://math.vcu.edu/programs/undergraduate/courses/math-placement/score-interpretation/prep-and-learning-modules/",
	mathAleksReport: "https://docs.google.com/forms/d/e/1FAIpQLSfJZ3ZLwSKBs3xx4UZLOC0CWjcfP3VuEQPjw0758dBtjF65Mw/viewform",
	chemAleks: "https://chemistry.vcu.edu/undergraduate/placement-test-and-aleks/",
	businessMajorChange: "https://docs.google.com/a/vcu.edu/forms/d/e/1FAIpQLSeIB9Ra9uM7ovgGnRDHNBXBsBdA6xbWNNIO6hIrJVNDBcrQlA/viewform",
	preMed: "https://bulletin.vcu.edu/undergraduate/college-humanities-sciences/prehealth-minors/pre-medicine/",
	physOverride: "https://docs.google.com/forms/d/e/1FAIpQLScjsYVNN-SSIUcAIuGXs2J0CQ_uwLppBPmqdCvzQU7kDaSjlQ/viewform",
	mathOverride: "https://math.vcu.edu/programs/undergraduate/courses/overrides/",
	chemOverride: "https://chemistry.vcu.edu/current-students/undergraduate/overrides/",
	mathHelpCenter: 'https://math.vcu.edu/current-students/help-center/',
	engCareerServices: 'https://egr.vcu.edu/current-students/career-services/students/',
	handshake: 'https://vcu.joinhandshake.com/login',
	preProfHealth: 'https://chs.vcu.edu/academics/undergraduate-studies/pre-professional-health-minors/',
	preProfHealthAdvising: 'https://careers.vcu.edu/preprofessionalhealth/',
	preProfHealthInquiry: 'https://docs.google.com/forms/d/e/1FAIpQLScCckwkuHYjBPOhSmubD8hVgzrAhxZVF3vmOyjtTMT8kpQi4A/viewform',
	vip: 'https://vip.vcu.edu/',
	research: 'https://egr.vcu.edu/research/student-research-opportunities/',
	researchNational: 'https://new.nsf.gov/funding/initiatives/reu/students',
	engStudentOrgs: 'https://egr.vcu.edu/current-students/student-organizations/',
	
	coursicle: 'https://www.coursicle.com/vcu/',
	
	financialAid: 'https://sfs.vcu.edu/',
	financialAidContact: 'https://sfs.vcu.edu/about/contact-us/',	
	writing: 'https://writing.vcu.edu/',
	military: 'https://militaryservices.vcu.edu/',
	transfer: 'https://transfer.vcu.edu/',
	disability: 'https://saeo.vcu.edu/',
	counseling: 'https://counseling.vcu.edu/',
	dosa: 'https://dos.vcu.edu/',
	advocacy: 'https://advocacy.vcu.edu/',
	learning: 'https://clc.vcu.edu/',
	global: 'https://global.vcu.edu/',
	health: 'https://health.students.vcu.edu/',
	housing: 'https://housing.vcu.edu/',
	
	ferpa: "https://studentprivacy.ed.gov/ferpa",
	ferpaVcu: 'https://registrar.vcu.edu/records/family-educational-rights-and-privacy-act/',
	//studentFerpaPdf: https://registrar.vcu.edu/media/registrar/forms/RARFERPA_Student_Consent_2024(3)(2).pdf,
	//studentFerpaGoogle: https://docs.google.com/forms/d/e/1FAIpQLSfGAbd0IGz2eDXX4ikQQMrJuhsKh-191h80Ymh2PFo90F_iQw/viewform,
	//parentFerpa: https://registrar.vcu.edu/media/registrar/forms/ParentFERPA(1).pdf,

	//Holds
	immunization: 'https://health.students.vcu.edu/immunizations/submitting-immunization-records/',
}

function linkIt(link, text) {
	return '<a href="' + link + '" target="_blank">' + text + '</a>';
};